# -*- coding: utf-8 -*-
"""Practico 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16niT3FKOef0tjpZ-FhateWhP9v6046TW
"""

from google.colab import files
carga = files.upload()

import pandas as pd
df = pd.read_csv("results.csv")
df.head()

df.info()

#limpiamos los datos de home score y away score ya que tienen nulos
df = df.dropna(subset=["home_score", "away_score"])

#verificamos que ya esté limpio
df.info()

#convertimos los tipos de datos home score y away score a enteros, ya que son los goles de local y visitante
df["home_score"] = df["home_score"].astype(int)
df["away_score"] = df["away_score"].astype(int)

#verificamos los cambios
df.info()

#vemos cuantos países se encuentran en la lista
#obtenemos todos los equipos que han jugado
teamsi = pd.unique(df[[
    'home_team',
    'away_team'
]].values.ravel())
len(teamsi)

#creamos el vector que obtendrá todos los equipos participantes
worldcup_teams = [
    "Canada", "Mexico", "United States", "Argentina", "Brazil",
    "Colombia", "Ecuador", "Paraguay", "Uruguay", "Austria",
    "Belgium", "Bosnia and Herzegovina", "Croatia", "Czech Republic", "England",
    "France", "Germany", "Netherlands", "Norway", "Portugal",
    "Scotland", "Spain", "Sweden", "Switzerland", "Turkey",
    "Algeria", "Cape Verde", "Congo DR", "Côte d'Ivoire", "Egypt",
    "Ghana", "Morocco", "Senegal", "South Africa", "Tunisia",
    "Australia", "Iran", "Iraq", "Japan", "Jordan",
    "South Korea","Qatar", "Saudi Arabia", "Uzbekistan", "Curaçao",
    "Haiti", "Panama", "New Zealand"
    ]

#normalizamos los nombres de los equipos
df["home_team"] = df["home_team"].replace({
    "DR Congo": "Congo DR",
    "Ivory Coast": "Côte d'Ivoire",
})

df["away_team"] = df["away_team"].replace({
    "DR Congo": "Congo DR",
    "Ivory Coast": "Côte d'Ivoire",
})

#definimos un campo donde nos guarde el ganador local, visitante o si fue empate
def get_result(row):
    if row["home_score"] > row["away_score"]:
        return 0  # local gana
    elif row["home_score"] < row["away_score"]:
        return 2  # visitante gana
    else:
        return 1  # empate

df["target"] = df.apply(get_result, axis=1)

#filtramos los equipos pertenecientes al ranking de la FIFA
df_wc = df[
    df["home_team"].isin(worldcup_teams) &
    df["away_team"].isin(worldcup_teams)
].copy()

sorted(df_wc["home_team"].unique())

sorted(df_wc["away_team"].unique())

#verificamos la lista
df_wc.shape

df_wc["home_team"].nunique()

df_wc["away_team"].nunique()

#verificamos la creación de la columna
df_wc[["home_team",
    "home_score",
    "away_team",
    "away_score",
    "target"]].head()

#verificamos la cantidad de victorias por visitante, local y empates
df_wc["target"].value_counts()

#verificamos la proporción de las victorias obtenidas en porcentaje
df_wc["target"].value_counts(normalize=True) * 100

#calculamos las estadísticas por equipo
teams = pd.unique(df_wc[[
    'home_team',
    'away_team'
]].values.ravel())
len(teams)

#inicializamos un contenedor vacío.
team_stats = {}

#calculamos las estadísticas por equipo
for team in teams:

  #calculamos cuando juega en local y cuando en visitante
  home = df_wc[df_wc["home_team"] == team]
  away = df_wc[df_wc["away_team"] == team]

  #calculamos las victorias que tuvo el equipo
  wins = (
      (home["home_score"]> home["away_score"]).sum()+
      (away["away_score"]>away["home_score"]).sum()
  )

  #caluclamos cuantos partidos jugó el equipo.
  matches = len(home)+len(away)

  #obtenemos la cantidad de coles
  goals_scored = home["home_score"].sum() + away["away_score"].sum()

  #obtenemos la proporción de partidos ganados por equipo
  winrate = wins / matches if matches > 0 else 0
  #caluclamos los goles promedio por partido
  avg_goals = goals_scored / matches if matches > 0 else 0

  #guardamos en el diccionario
  team_stats[team] = {
      "winrate" : winrate,
      "avg_goals": avg_goals,
      "matches" : matches
  }

set(team_stats.keys()) - set(worldcup_teams)

#verificamos los equipos mas fuertes
stats_df = pd.DataFrame.from_dict(team_stats, orient="index")
stats_df.sort_values("winrate", ascending=False).head(10)

#verificamos los datos
stats_df = pd.DataFrame.from_dict(team_stats, orient="index")
stats_df.head()

#vemos los 10 equipos mas fuertes
stats_df.sort_values("winrate", ascending=False).head(10)

def get_features(row):
  #extraemos los equipos
  home = row["home_team"]
  away = row["away_team"]

#calculamos, winrate: diferencia de fuerza histórica
#avg_goals: diferencia de ataque
#neutral: campo del local, o no es de ninguno
  return pd.Series([
      team_stats[home]["winrate"] - team_stats[away]["winrate"],
      team_stats[home]["avg_goals"] - team_stats[away]["avg_goals"],
      row["neutral"]
  ])

#aplicamos los features al dataset, convertimos los partidos en numeros
#predecimos quien es mejor+que tan parejo es el partido
X = df_wc.apply(get_features, axis=1)
X.columns = ["winrate_diff", "goals_diff", "neutral"]

X["abs_winrate_diff"] = X["winrate_diff"].abs()
X["abs_goals_diff"] = X["goals_diff"].abs()

X["home_stronger"] = (X["winrate_diff"]>0).astype(int)
X["strength_combined"] = X["winrate_diff"] * X["goals_diff"]
X["match_balance"] = (X["abs_winrate_diff"] + X["abs_goals_diff"])

#resultado
y = df_wc["target"]

#convertimos el X a entero
X=X.fillna(0)
X["neutral"] = X["neutral"].astype(int)

X.head()

X.describe()

#debemos visualizar el resultado conjunto
pd.concat([X, df_wc["target"]], axis=1).head()

#visualizamos la distribución rápida de featrures
X["goals_diff"].hist()

X["winrate_diff"].hist()

#importamos los modelos Logistic Regression, Random Forest y XGBoost
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, log_loss

#separamos los datos 80% para aprendizaje, 20% para evaluar
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#entrenamos el modelo de regresión logística
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)
y_pred_lr2 = model.predict(X_test)
y_prob_lr2 = model.predict_proba(X_test)

print("Logistic regression - features")
print(classification_report(y_test, y_pred_lr2))
print(log_loss(y_test, y_prob_lr2))

model.coef_

#realizamos las predicciones
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)

#evaluamos
print(classification_report(y_test, y_pred))

model.n_iter_

#importamos el modelo XGBoost
from xgboost import XGBClassifier

#entrenamos el modelo
xgb_model = XGBClassifier(
    n_estimators=200,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)

#realizamos las predicciones
y_pred_xgb = xgb_model.predict(X_test)
y_prob_xgb = xgb_model.predict_proba(X_test)

#Evaluamos el modelo
print(classification_report(y_test, y_pred_xgb))
print(log_loss(y_test, y_prob_xgb))

#realizar la validación cruzada
from sklearn.model_selection import cross_val_score

#validación a la regresión logistica
cv_scores_lr = cross_val_score(
    model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("Logistic Regression - Validación Cruzada:")
print(cv_scores_lr)

print("Average Accuracy:")
print(cv_scores_lr.mean())

#Validacipion al XGBoost
cv_scores_xgb = cross_val_score(
    xgb_model,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print("XGBoost - Validación cruzada:")
print(cv_scores_xgb)

print("Average Accuracy:")
print(cv_scores_xgb.mean())

#simulación Monte Carlo
teams = list(worldcup_teams)

#Creamos un prtido
import random
import numpy as np

def simulate_match(team1, team2):
  winrate_diff=(
      team_stats[team1]["winrate"] -
      team_stats[team2]["winrate"]
  )

  goals_diff = (
      team_stats[team1]["avg_goals"] -
      team_stats[team2]["avg_goals"]
  )

  features = pd.DataFrame([{
        "winrate_diff": winrate_diff,
        "goals_diff": goals_diff,
        "neutral": 1,
        "abs_winrate_diff": abs(winrate_diff),
        "abs_goals_diff": abs(goals_diff),
        "home_stronger": int(winrate_diff > 0),
        "strength_combined": winrate_diff * goals_diff,
        "match_balance": (
            abs(winrate_diff) + abs(goals_diff)
        )
    }])

  #probabilidades del modelo
  probs = model.predict_proba(features)[0]

  #Elegimos resultado aleatorio
  outcome = np.random.choice(
        [0, 1, 2],
        p=probs
    )

#devolvemos al ganador
  if outcome == 0:
    return team1
  elif outcome == 2:
    return team2
  else:
    return random.choice([team1, team2])

#probamos un partido
simulate_match("Argentina", "Brazil")

#simulamos todo el torneo para sacar las probabilidades del campeon
#simulamos la primera ronda, tenemos 48 equipos, de los cuales saldran 24 ganadores
#segunda ronda, entran 24 equipos, salen 12 ganadores
#tercera ronda, 12 equipos, 8 ganadores
#cuartos de final 8 equpos, 4 ganadores
#semi final 4 equipos, 2 ganadores
#Final 2 equipos, 1 ganador

def simulate_tournament(teams):

    teams = teams.copy()

    random.shuffle(teams)

    while len(teams) > 1:

        if len(teams) % 2 == 1:
            teams.append(random.choice(teams))

        winners = []

        for i in range(0, len(teams), 2):

            team1 = teams[i]
            team2 = teams[i + 1]

            winner = simulate_match(team1, team2)

            winners.append(winner)

        teams = winners

    return teams[0]

#probamos un torneo
simulate_tournament(teams)

#Simulamos 10000 mundiales
champions = []

for i in range(10000):

    champion = simulate_tournament(teams)

    champions.append(champion)

#contamos los campeones
from collections import Counter

results = Counter(champions)

#vemos el top 10 de campeones
results.most_common(10)

#convertimos en probabilidades
total_simulations = len(champions)

final_results = []

for team in worldcup_teams:

    championships = results.get(team, 0)

    probability = (
        championships / total_simulations
    ) * 100

    final_results.append({

        "team": team,

        "championship_probability":
            round(probability, 2),

        "historical_winrate":
            round(team_stats[team]["winrate"] * 100, 2),

        "avg_goals":
            round(team_stats[team]["avg_goals"], 2),

        "matches":
            team_stats[team]["matches"]
    })

final_df = pd.DataFrame(final_results)

final_df.sort_values(
    "championship_probability",
    ascending=False
)

